### PR TITLE
fix: match_parameter function when result's parameter is nil.

### PR DESCRIPTION
**Pull request by hungrybirder**
Fix the https://github.com/ray-x/lsp_signature.nvim/issues/4

Please check it out.

Thank you.

### CODE REVIEW

**Comment by ray-x** [comment]
Thanks, Looks good

**Comment by favadi** [comment]
Not sure if I should open another ticket, I get the same error, but this time in https://github.com/ray-x/lsp_signature.nvim/blob/e909187641c9b5a6a58a27b469a441fa48986075/lua/lsp_signature.lua#L168.

**Comment by ray-x** [comment]
Could you send the code signature and the name of your lsp so I can reproduce the issue?

**Comment by favadi** [comment]
@ray-x I've update the plugin and seems that the error is gone away. Many thanks.

**Pull request merged**
